version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      frontend-minor-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-image-minor-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      backend-image-minor-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /backend/src/db
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-database-minor-patch:
        patterns: ['*']
        update-types: ['minor', 'patch']
    commit-message:
      prefix: build
