import type { Chat } from '../../stores/chatStore'

export function formatTimeAgo(timestamp: string): string {
  const now = Date.now()
  const time = new Date(timestamp).getTime()
  const diff = now - time
  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes}m ago`
  if (hours < 24) return `${hours}h ago`
  if (days < 7) return `${days}d ago`
  return new Date(timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

export function getChatDisplayTitle(chat: Chat): string {
  if (chat.autoGeneratedTitle && isGenericName(chat.name)) {
    return chat.autoGeneratedTitle
  }
  return chat.name || 'Untitled'
}

export function isGenericName(name: string | null | undefined): boolean {
  if (!name) return true
  const genericPatterns = [
    /^new chat$/i,
    /^untitled$/i,
    /^chat$/i,
    /^conversation$/i,
    /^\d{4}-\d{2}-\d{2}/,
    /^chat #?\d+$/i,
  ]
  return genericPatterns.some((pattern) => pattern.test(name.trim()))
}
