import { useState, useCallback, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useChatStore, useThemeStore } from '../../stores'
import type { Chat } from '../../stores/chatStore'
import { fetchMyChats } from '../../services/chat'
import { useAuthStore } from '../../stores/authStore'

function formatTimeAgo(timestamp: string): string {
  const now = Date.now()
  const time = new Date(timestamp).getTime()
  const diff = now - time
  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes}m ago`
  if (hours < 24) return `${hours}h ago`
  if (days < 7) return `${days}d ago`
  return new Date(timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

function getChatDisplayTitle(chat: Chat): string {
  if (chat.autoGeneratedTitle && isGenericName(chat.name)) {
    return chat.autoGeneratedTitle
  }
  return chat.name || 'Untitled'
}

function isGenericName(name: string | null | undefined): boolean {
  if (!name) return true
  const genericPatterns = [
    /^new chat$/i,
    /^untitled$/i,
    /^chat$/i,
    /^conversation$/i,
    /^\d{4}-\d{2}-\d{2}/,
    /^chat #?\d+$/i,
  ]
  return genericPatterns.some((pattern) => pattern.test(name.trim()))
}

interface ChatHistorySidebarProps {
  isOpen: boolean
  onClose: () => void
  currentChatId?: string
}

export default function ChatHistorySidebar({ isOpen, onClose, currentChatId }: ChatHistorySidebarProps) {
  const { theme } = useThemeStore()
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { chats, setChats, setActiveChat } = useChatStore()
  const { isAuthenticated, user, _hasHydrated } = useAuthStore()

  const [isLoading, setIsLoading] = useState(false)
  const [totalChats, setTotalChats] = useState(0)
  const sidebarRef = useRef<HTMLDivElement>(null)
  const prevAuthState = useRef<{ isAuth: boolean; userId?: string } | null>(null)

  // Load chats
  const loadChats = useCallback(async () => {
    if (isLoading) return
    setIsLoading(true)
    try {
      const { chats: newChats, total } = await fetchMyChats({ limit: 20 })
      setTotalChats(total)

      // Merge with existing chats to preserve local state
      const existingChatsMap = new Map(chats.map(c => [c.id, c]))
      const mergedChats = newChats.map(apiChat => {
        const existing = existingChatsMap.get(apiChat.id)
        if (existing) {
          return { ...apiChat, messages: existing.messages, members: existing.members }
        }
        return apiChat
      })
      setChats(mergedChats)
    } catch (error) {
      console.error('Failed to load chats:', error)
    } finally {
      setIsLoading(false)
    }
  }, [isLoading, setChats, chats])

  // Load chats on mount and when sidebar opens
  useEffect(() => {
    if (isOpen) {
      loadChats()
    }
  }, [isOpen]) // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-reload on user sign in
  useEffect(() => {
    if (!_hasHydrated) return

    const currentAuthState = {
      isAuth: isAuthenticated(),
      userId: user?.id
    }

    // Check if auth state changed (user signed in)
    if (prevAuthState.current !== null) {
      const wasNotAuthenticated = !prevAuthState.current.isAuth
      const isNowAuthenticated = currentAuthState.isAuth
      const userChanged = prevAuthState.current.userId !== currentAuthState.userId

      if ((wasNotAuthenticated && isNowAuthenticated) || userChanged) {
        // User just signed in - reload chats
        console.log('[ChatHistorySidebar] Auth state changed, reloading chats')
        loadChats()
      }
    }

    prevAuthState.current = currentAuthState
  }, [_hasHydrated, isAuthenticated, user?.id, loadChats])

  // Listen for managed auth success event
  useEffect(() => {
    const handleAuthSuccess = () => {
      console.log('[ChatHistorySidebar] Auth success event, reloading chats')
      // Small delay to let the auth state settle
      setTimeout(() => loadChats(), 200)
    }

    window.addEventListener('juice:managed-auth-success', handleAuthSuccess)
    window.addEventListener('juice:siwe-signed-in', handleAuthSuccess)
    window.addEventListener('juice:passkey-connected', handleAuthSuccess)

    return () => {
      window.removeEventListener('juice:managed-auth-success', handleAuthSuccess)
      window.removeEventListener('juice:siwe-signed-in', handleAuthSuccess)
      window.removeEventListener('juice:passkey-connected', handleAuthSuccess)
    }
  }, [loadChats])

  // Close on click outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (isOpen && sidebarRef.current && !sidebarRef.current.contains(e.target as Node)) {
        onClose()
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [isOpen, onClose])

  // Close on escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose()
      }
    }

    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [isOpen, onClose])

  const handleSelectChat = (chatId: string) => {
    setActiveChat(chatId)
    navigate(`/chat/${chatId}`)
    onClose()
  }

  const handleNewChat = () => {
    setActiveChat(null)
    navigate('/')
    onClose()
  }

  // Sort chats: pinned first, then by updatedAt (filter out null/undefined)
  const sortedChats = [...chats].filter(Boolean).sort((a, b) => {
    if (a.isPinned && !b.isPinned) return -1
    if (!a.isPinned && b.isPinned) return 1
    return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  })

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/30 z-40 transition-opacity"
          onClick={onClose}
        />
      )}

      {/* Sidebar */}
      <div
        ref={sidebarRef}
        className={`fixed top-0 left-0 h-full w-72 z-50 transform transition-transform duration-200 ease-out ${
          isOpen ? 'translate-x-0' : '-translate-x-full'
        } ${
          theme === 'dark'
            ? 'bg-juice-dark border-r border-white/10'
            : 'bg-white border-r border-gray-200'
        }`}
      >
        {/* Header */}
        <div className={`flex items-center justify-between p-4 border-b ${
          theme === 'dark' ? 'border-white/10' : 'border-gray-200'
        }`}>
          <h2 className={`text-sm font-semibold ${
            theme === 'dark' ? 'text-white' : 'text-gray-900'
          }`}>
            {t('ui.recent', 'Recent')} {totalChats > 0 && `(${totalChats})`}
          </h2>
          <div className="flex items-center gap-2">
            {/* New chat button */}
            <button
              onClick={handleNewChat}
              className={`p-1.5 transition-colors ${
                theme === 'dark'
                  ? 'text-gray-400 hover:text-white hover:bg-white/10'
                  : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
              }`}
              title={t('chat.newChat', 'New Chat')}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
              </svg>
            </button>
            {/* Close button */}
            <button
              onClick={onClose}
              className={`p-1.5 transition-colors ${
                theme === 'dark'
                  ? 'text-gray-400 hover:text-white hover:bg-white/10'
                  : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
              }`}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Chat list */}
        <div className="flex-1 overflow-y-auto h-[calc(100%-60px)]">
          {isLoading && chats.length === 0 ? (
            <div className="p-4 text-center">
              <div className={`text-sm ${
                theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
              }`}>
                {t('ui.loading', 'Loading...')}
              </div>
            </div>
          ) : sortedChats.length === 0 ? (
            <div className="p-4 text-center">
              <div className={`text-sm ${
                theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
              }`}>
                {t('chat.noChats', 'No chats yet')}
              </div>
              <button
                onClick={handleNewChat}
                className="mt-2 text-sm text-juice-orange hover:underline"
              >
                {t('chat.createFirst', 'Start a new chat')}
              </button>
            </div>
          ) : (
            <div className="py-2">
              {sortedChats.map((chat) => (
                <button
                  key={chat.id}
                  onClick={() => handleSelectChat(chat.id)}
                  className={`w-full px-4 py-3 text-left transition-colors ${
                    chat.id === currentChatId
                      ? theme === 'dark'
                        ? 'bg-white/10 border-l-2 border-juice-orange'
                        : 'bg-gray-100 border-l-2 border-juice-orange'
                      : theme === 'dark'
                        ? 'hover:bg-white/5'
                        : 'hover:bg-gray-50'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    {/* Pin indicator */}
                    {chat.isPinned && (
                      <svg className={`w-3 h-3 shrink-0 mt-1 ${
                        theme === 'dark' ? 'text-purple-400' : 'text-purple-600'
                      }`} viewBox="0 0 24 24" fill="currentColor">
                        <path d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
                      </svg>
                    )}

                    {/* Chat info */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2">
                        <span className={`text-sm font-medium truncate ${
                          chat.id === currentChatId
                            ? theme === 'dark' ? 'text-white' : 'text-gray-900'
                            : theme === 'dark' ? 'text-gray-200' : 'text-gray-700'
                        }`}>
                          {getChatDisplayTitle(chat)}
                        </span>
                        <span className={`text-xs shrink-0 ${
                          theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                        }`}>
                          {formatTimeAgo(chat.updatedAt)}
                        </span>
                      </div>
                      {chat.description && (
                        <div className={`text-xs truncate mt-0.5 ${
                          theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                        }`}>
                          {chat.description}
                        </div>
                      )}
                      {/* Unread badge */}
                      {chat.unreadCount && chat.unreadCount > 0 && (
                        <span className="inline-block mt-1 px-1.5 py-0.5 text-xs font-medium bg-juice-orange text-white rounded-full">
                          {chat.unreadCount} new
                        </span>
                      )}
                    </div>
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
    </>
  )
}
