import { useState, useCallback, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useAccount } from 'wagmi'
import { useChatStore, useThemeStore } from '../../stores'
import type { Chat } from '../../stores/chatStore'
import { fetchMyChats } from '../../services/chat'
import { fetchProjectsByOwner, clearProjectsByOwnerCache, type Project } from '../../services/bendystraw'
import { useAuthStore } from '../../stores/authStore'
import { useManagedWallet } from '../../hooks'
import { resolveIpfsUri } from '../../utils/ipfs'
import { CHAINS } from '../../constants'
import {
  getOwnerConversations,
  getSupporterConversations,
  type ProjectConversation,
} from '../../api/projectConversations'

type SidebarTab = 'chats' | 'projects' | 'payments'

function formatTimeAgo(timestamp: string | number): string {
  const now = Date.now()
  const time = typeof timestamp === 'string' ? new Date(timestamp).getTime() : timestamp * 1000
  const diff = now - time
  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes}m ago`
  if (hours < 24) return `${hours}h ago`
  if (days < 7) return `${days}d ago`
  return new Date(time).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

function getChatDisplayTitle(chat: Chat): string {
  if (chat.autoGeneratedTitle && isGenericName(chat.name)) {
    return chat.autoGeneratedTitle
  }
  return chat.name || 'Untitled'
}

function isGenericName(name: string | null | undefined): boolean {
  if (!name) return true
  const genericPatterns = [
    /^new chat$/i,
    /^untitled$/i,
    /^chat$/i,
    /^conversation$/i,
    /^\d{4}-\d{2}-\d{2}/,
    /^chat #?\d+$/i,
  ]
  return genericPatterns.some((pattern) => pattern.test(name.trim()))
}

function formatVolume(volumeUsd: number | string | null | undefined): string {
  if (!volumeUsd) return '$0'
  const num = typeof volumeUsd === 'string' ? parseFloat(volumeUsd) : volumeUsd
  if (num >= 1000000) return `$${(num / 1000000).toFixed(1)}M`
  if (num >= 1000) return `$${(num / 1000).toFixed(1)}K`
  return `$${num.toFixed(0)}`
}

function formatAddress(address: string): string {
  return `${address.slice(0, 6)}...${address.slice(-4)}`
}

function formatWei(wei: string): string {
  const num = parseFloat(wei) / 1e18
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`
  if (num >= 1) return num.toFixed(2)
  return num.toFixed(4)
}

interface ChatHistorySidebarProps {
  isOpen: boolean
  onClose: () => void
  currentChatId?: string
}

export default function ChatHistorySidebar({ isOpen, onClose, currentChatId }: ChatHistorySidebarProps) {
  const { theme } = useThemeStore()
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { chats, setChats, setActiveChat } = useChatStore()
  const { isAuthenticated, user, _hasHydrated } = useAuthStore()
  const { address: wagmiAddress, isConnected: wagmiConnected } = useAccount()
  const { address: managedAddress, isManagedMode, loading: managedWalletLoading } = useManagedWallet()

  // User has wallet access if connected via wagmi OR authenticated via managed wallet
  // Wait for auth store hydration before determining wallet access
  const hasWalletAccess = wagmiConnected || isManagedMode
  const activeAddress = wagmiConnected ? wagmiAddress : managedAddress
  // Still loading if auth store hasn't hydrated or managed wallet is loading
  const isWalletAccessLoading = !_hasHydrated || managedWalletLoading

  const [activeTab, setActiveTab] = useState<SidebarTab>('chats')
  const [isLoading, setIsLoading] = useState(false)
  const [totalChats, setTotalChats] = useState(0)

  // Projects tab state
  const [ownedProjects, setOwnedProjects] = useState<Project[]>([])
  const [projectsLoading, setProjectsLoading] = useState(false)
  const [projectsLoaded, setProjectsLoaded] = useState(false)
  const [expandedProjectId, setExpandedProjectId] = useState<string | null>(null)
  const [projectSupporters, setProjectSupporters] = useState<Record<string, ProjectConversation[]>>({})
  const [supportersLoading, setSupportersLoading] = useState<string | null>(null)

  // Payments tab state (for supporters)
  const [supporterConversations, setSupporterConversations] = useState<ProjectConversation[]>([])
  const [paymentsLoading, setPaymentsLoading] = useState(false)
  const [paymentsLoaded, setPaymentsLoaded] = useState(false)

  const sidebarRef = useRef<HTMLDivElement>(null)
  const prevAuthState = useRef<{ isAuth: boolean; userId?: string } | null>(null)

  // Load chats
  const loadChats = useCallback(async () => {
    if (isLoading) return
    setIsLoading(true)
    try {
      const { chats: newChats, total } = await fetchMyChats({ limit: 20 })
      setTotalChats(total)

      const existingChatsMap = new Map(chats.map(c => [c.id, c]))
      const mergedChats = newChats.map(apiChat => {
        const existing = existingChatsMap.get(apiChat.id)
        if (existing) {
          return { ...apiChat, messages: existing.messages, members: existing.members }
        }
        return apiChat
      })
      setChats(mergedChats)
    } catch (error) {
      console.error('Failed to load chats:', error)
    } finally {
      setIsLoading(false)
    }
  }, [isLoading, setChats, chats])

  // Load owned projects
  const loadProjects = useCallback(async (forceRefresh = false) => {
    if (!activeAddress || projectsLoading) return
    // Clear cache if force refreshing (e.g., after deploying a new project)
    if (forceRefresh) {
      clearProjectsByOwnerCache(activeAddress)
    }
    setProjectsLoading(true)
    try {
      const projects = await fetchProjectsByOwner(activeAddress)
      setOwnedProjects(projects)
      setProjectsLoaded(true)
    } catch (error) {
      console.error('Failed to load owned projects:', error)
    } finally {
      setProjectsLoading(false)
    }
  }, [activeAddress, projectsLoading])

  // Load supporters for a project
  const loadSupporters = useCallback(async (project: Project) => {
    const projectKey = `${project.projectId}-${project.chainId}`
    if (supportersLoading === projectKey || projectSupporters[projectKey]) return

    setSupportersLoading(projectKey)
    try {
      const result = await getOwnerConversations({
        projectId: project.projectId,
        chainId: project.chainId,
        limit: 20,
      })
      setProjectSupporters(prev => ({
        ...prev,
        [projectKey]: result.conversations,
      }))
    } catch (error) {
      console.error('Failed to load supporters:', error)
    } finally {
      setSupportersLoading(null)
    }
  }, [supportersLoading, projectSupporters])

  // Load supporter conversations (payments tab)
  const loadPayments = useCallback(async () => {
    if (!activeAddress || paymentsLoading) return
    setPaymentsLoading(true)
    try {
      const result = await getSupporterConversations({ limit: 50 })
      setSupporterConversations(result.conversations)
      setPaymentsLoaded(true)
    } catch (error) {
      console.error('Failed to load payment conversations:', error)
    } finally {
      setPaymentsLoading(false)
    }
  }, [activeAddress, paymentsLoading])

  // Load chats on mount and when sidebar opens
  useEffect(() => {
    if (isOpen && activeTab === 'chats') {
      loadChats()
    }
  }, [isOpen, activeTab]) // eslint-disable-line react-hooks/exhaustive-deps

  // Load projects when tab switches
  useEffect(() => {
    if (isOpen && activeTab === 'projects' && activeAddress && !projectsLoaded) {
      loadProjects()
    }
  }, [isOpen, activeTab, activeAddress, projectsLoaded]) // eslint-disable-line react-hooks/exhaustive-deps

  // Load payments when tab switches
  useEffect(() => {
    if (isOpen && activeTab === 'payments' && activeAddress && !paymentsLoaded) {
      loadPayments()
    }
  }, [isOpen, activeTab, activeAddress, paymentsLoaded]) // eslint-disable-line react-hooks/exhaustive-deps

  // Reset state when address changes
  useEffect(() => {
    setProjectsLoaded(false)
    setOwnedProjects([])
    setPaymentsLoaded(false)
    setSupporterConversations([])
    setProjectSupporters({})
    setExpandedProjectId(null)
  }, [activeAddress])

  // Auto-reload on user sign in
  useEffect(() => {
    if (!_hasHydrated) return

    const currentAuthState = {
      isAuth: isAuthenticated(),
      userId: user?.id
    }

    if (prevAuthState.current !== null) {
      const wasNotAuthenticated = !prevAuthState.current.isAuth
      const isNowAuthenticated = currentAuthState.isAuth
      const userChanged = prevAuthState.current.userId !== currentAuthState.userId

      if ((wasNotAuthenticated && isNowAuthenticated) || userChanged) {
        console.log('[ChatHistorySidebar] Auth state changed, reloading chats')
        loadChats()
      }
    }

    prevAuthState.current = currentAuthState
  }, [_hasHydrated, isAuthenticated, user?.id, loadChats])

  // Listen for managed auth success event
  useEffect(() => {
    const handleAuthSuccess = () => {
      console.log('[ChatHistorySidebar] Auth success event, reloading chats')
      setTimeout(() => loadChats(), 200)
    }

    window.addEventListener('juice:managed-auth-success', handleAuthSuccess)
    window.addEventListener('juice:siwe-signed-in', handleAuthSuccess)
    window.addEventListener('juice:passkey-connected', handleAuthSuccess)

    return () => {
      window.removeEventListener('juice:managed-auth-success', handleAuthSuccess)
      window.removeEventListener('juice:siwe-signed-in', handleAuthSuccess)
      window.removeEventListener('juice:passkey-connected', handleAuthSuccess)
    }
  }, [loadChats])

  // Close on click outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (isOpen && sidebarRef.current && !sidebarRef.current.contains(e.target as Node)) {
        onClose()
      }
    }

    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [isOpen, onClose])

  // Close on escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose()
      }
    }

    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [isOpen, onClose])

  const handleSelectChat = (chatId: string) => {
    setActiveChat(chatId)
    navigate(`/chat/${chatId}`)
    onClose()
  }

  const handleNewChat = () => {
    setActiveChat(null)
    navigate('/')
    onClose()
  }

  const handleToggleProject = (project: Project) => {
    const projectKey = `${project.projectId}-${project.chainId}`
    if (expandedProjectId === projectKey) {
      setExpandedProjectId(null)
    } else {
      setExpandedProjectId(projectKey)
      loadSupporters(project)
    }
  }

  const handleSelectConversation = (conversation: ProjectConversation) => {
    // Navigate to the conversation's underlying chat
    setActiveChat(conversation.chatId)
    navigate(`/chat/${conversation.chatId}`)
    onClose()
  }

  // Sort chats
  const sortedChats = [...chats].filter(Boolean).sort((a, b) => {
    if (a.isPinned && !b.isPinned) return -1
    if (!a.isPinned && b.isPinned) return 1
    return new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  })

  const getTabLabel = () => {
    switch (activeTab) {
      case 'chats': return t('ui.recentConversations', 'Recent conversations')
      case 'projects': return t('ui.projectsYouOwn', 'Projects you own')
      case 'payments': return t('ui.projectsYouSupport', 'Projects you support')
    }
  }

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/30 z-40 transition-opacity"
          onClick={onClose}
        />
      )}

      {/* Sidebar */}
      <div
        ref={sidebarRef}
        className={`fixed top-0 left-0 h-full w-80 z-50 transform transition-transform duration-200 ease-out flex flex-col ${
          isOpen ? 'translate-x-0' : '-translate-x-full'
        } ${
          theme === 'dark'
            ? 'bg-juice-dark border-r border-white/10'
            : 'bg-white border-r border-gray-200'
        }`}
      >
        {/* Header with tabs */}
        <div className={`border-b ${theme === 'dark' ? 'border-white/10' : 'border-gray-200'}`}>
          {/* Tab bar */}
          <div className="flex">
            <button
              onClick={() => setActiveTab('chats')}
              className={`flex-1 px-2 py-3 text-xs font-medium transition-colors ${
                activeTab === 'chats'
                  ? theme === 'dark'
                    ? 'text-white border-b-2 border-juice-orange'
                    : 'text-gray-900 border-b-2 border-juice-orange'
                  : theme === 'dark'
                    ? 'text-gray-400 hover:text-gray-200'
                    : 'text-gray-500 hover:text-gray-700'
              }`}
            >
              {t('ui.chats', 'Chats')}
            </button>
            <button
              onClick={() => setActiveTab('projects')}
              className={`flex-1 px-2 py-3 text-xs font-medium transition-colors ${
                activeTab === 'projects'
                  ? theme === 'dark'
                    ? 'text-white border-b-2 border-juice-orange'
                    : 'text-gray-900 border-b-2 border-juice-orange'
                  : theme === 'dark'
                    ? 'text-gray-400 hover:text-gray-200'
                    : 'text-gray-500 hover:text-gray-700'
              }`}
            >
              {t('ui.myProjects', 'My Projects')}
            </button>
            <button
              onClick={() => setActiveTab('payments')}
              className={`flex-1 px-2 py-3 text-xs font-medium transition-colors ${
                activeTab === 'payments'
                  ? theme === 'dark'
                    ? 'text-white border-b-2 border-juice-orange'
                    : 'text-gray-900 border-b-2 border-juice-orange'
                  : theme === 'dark'
                    ? 'text-gray-400 hover:text-gray-200'
                    : 'text-gray-500 hover:text-gray-700'
              }`}
            >
              {t('ui.payments', 'Payments')}
            </button>
          </div>

          {/* Action buttons */}
          <div className={`flex items-center justify-between px-4 py-2 ${
            theme === 'dark' ? 'bg-white/5' : 'bg-gray-50'
          }`}>
            <span className={`text-xs ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
              {getTabLabel()}
            </span>
            <div className="flex items-center gap-1">
              {activeTab === 'chats' && (
                <button
                  onClick={handleNewChat}
                  className={`p-1.5 rounded transition-colors ${
                    theme === 'dark'
                      ? 'text-gray-400 hover:text-white hover:bg-white/10'
                      : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
                  }`}
                  title={t('chat.newChat', 'New Chat')}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                </button>
              )}
              {activeTab === 'projects' && hasWalletAccess && (
                <button
                  onClick={() => loadProjects(true)}
                  className={`p-1.5 rounded transition-colors ${
                    theme === 'dark'
                      ? 'text-gray-400 hover:text-white hover:bg-white/10'
                      : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
                  }`}
                  title={t('ui.refresh', 'Refresh')}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                </button>
              )}
              <button
                onClick={onClose}
                className={`p-1.5 rounded transition-colors ${
                  theme === 'dark'
                    ? 'text-gray-400 hover:text-white hover:bg-white/10'
                    : 'text-gray-500 hover:text-gray-700 hover:bg-gray-100'
                }`}
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        {/* Content area */}
        <div className="flex-1 overflow-y-auto">
          {/* Chats Tab */}
          {activeTab === 'chats' && (
            <>
              {isLoading && chats.length === 0 ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('ui.loading', 'Loading...')}
                  </div>
                </div>
              ) : sortedChats.length === 0 ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('chat.noChats', 'No chats yet')}
                  </div>
                  <button
                    onClick={handleNewChat}
                    className="mt-2 text-sm text-juice-orange hover:underline"
                  >
                    {t('chat.createFirst', 'Start a new chat')}
                  </button>
                </div>
              ) : (
                <div className="py-2">
                  {sortedChats.map((chat) => (
                    <button
                      key={chat.id}
                      onClick={() => handleSelectChat(chat.id)}
                      className={`w-full px-4 py-3 text-left transition-colors ${
                        chat.id === currentChatId
                          ? theme === 'dark'
                            ? 'bg-white/10 border-l-2 border-juice-orange'
                            : 'bg-gray-100 border-l-2 border-juice-orange'
                          : theme === 'dark'
                            ? 'hover:bg-white/5'
                            : 'hover:bg-gray-50'
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        {chat.isPinned && (
                          <svg className={`w-3 h-3 shrink-0 mt-1 ${
                            theme === 'dark' ? 'text-purple-400' : 'text-purple-600'
                          }`} viewBox="0 0 24 24" fill="currentColor">
                            <path d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
                          </svg>
                        )}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between gap-2">
                            <span className={`text-sm font-medium truncate ${
                              chat.id === currentChatId
                                ? theme === 'dark' ? 'text-white' : 'text-gray-900'
                                : theme === 'dark' ? 'text-gray-200' : 'text-gray-700'
                            }`}>
                              {getChatDisplayTitle(chat)}
                            </span>
                            <span className={`text-xs shrink-0 ${
                              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                            }`}>
                              {formatTimeAgo(chat.updatedAt)}
                            </span>
                          </div>
                          {chat.description && (
                            <div className={`text-xs truncate mt-0.5 ${
                              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                            }`}>
                              {chat.description}
                            </div>
                          )}
                          {chat.unreadCount && chat.unreadCount > 0 && (
                            <span className="inline-block mt-1 px-1.5 py-0.5 text-xs font-medium bg-juice-orange text-white rounded-full">
                              {chat.unreadCount} new
                            </span>
                          )}
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </>
          )}

          {/* Projects Tab */}
          {activeTab === 'projects' && (
            <>
              {isWalletAccessLoading ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('ui.loading', 'Loading...')}
                  </div>
                </div>
              ) : !hasWalletAccess ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('wallet.connectToSeeProjects', 'Connect wallet to see your projects')}
                  </div>
                  <button
                    onClick={() => window.dispatchEvent(new CustomEvent('juice:open-wallet-panel'))}
                    className="mt-2 text-sm text-juice-orange hover:underline"
                  >
                    {t('wallet.connect', 'Connect Wallet')}
                  </button>
                </div>
              ) : projectsLoading ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('ui.loading', 'Loading...')}
                  </div>
                </div>
              ) : ownedProjects.length === 0 ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('projects.noOwned', 'You don\'t own any projects yet')}
                  </div>
                  <div className="flex items-center justify-center gap-3 mt-2">
                    <button
                      onClick={handleNewChat}
                      className="text-sm text-juice-orange hover:underline"
                    >
                      {t('projects.launchFirst', 'Launch a project')}
                    </button>
                    <span className={`text-xs ${theme === 'dark' ? 'text-gray-600' : 'text-gray-400'}`}>or</span>
                    <button
                      onClick={() => loadProjects(true)}
                      className={`text-sm ${theme === 'dark' ? 'text-gray-400 hover:text-white' : 'text-gray-500 hover:text-gray-700'} flex items-center gap-1`}
                    >
                      <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                      </svg>
                      {t('ui.refresh', 'Refresh')}
                    </button>
                  </div>
                </div>
              ) : (
                <div className="py-2">
                  {ownedProjects.map((project) => {
                    const projectKey = `${project.projectId}-${project.chainId}`
                    const isExpanded = expandedProjectId === projectKey
                    const supporters = projectSupporters[projectKey] || []
                    const isLoadingSupporters = supportersLoading === projectKey

                    return (
                      <div key={project.id}>
                        {/* Project row */}
                        <button
                          onClick={() => handleToggleProject(project)}
                          className={`w-full px-4 py-3 text-left transition-colors ${
                            theme === 'dark' ? 'hover:bg-white/5' : 'hover:bg-gray-50'
                          }`}
                        >
                          <div className="flex items-start gap-3">
                            {/* Expand chevron */}
                            <svg
                              className={`w-4 h-4 shrink-0 mt-1 transition-transform ${
                                isExpanded ? 'rotate-90' : ''
                              } ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`}
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                            </svg>

                            {/* Project logo */}
                            {project.logoUri ? (
                              <img
                                src={resolveIpfsUri(project.logoUri) ?? ''}
                                alt=""
                                className="w-8 h-8 rounded-lg object-cover shrink-0"
                                onError={(e) => {
                                  (e.target as HTMLImageElement).style.display = 'none'
                                }}
                              />
                            ) : (
                              <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${
                                theme === 'dark' ? 'bg-white/10' : 'bg-gray-100'
                              }`}>
                                <span className={`text-sm font-medium ${
                                  theme === 'dark' ? 'text-gray-400' : 'text-gray-500'
                                }`}>
                                  {(project.name || 'P')[0].toUpperCase()}
                                </span>
                              </div>
                            )}

                            {/* Project info */}
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center justify-between gap-2">
                                <span className={`text-sm font-medium truncate ${
                                  theme === 'dark' ? 'text-gray-200' : 'text-gray-700'
                                }`}>
                                  {project.name || `Project #${project.projectId}`}
                                </span>
                                <span className={`text-xs shrink-0 px-1.5 py-0.5 rounded ${
                                  theme === 'dark' ? 'bg-white/10 text-gray-400' : 'bg-gray-100 text-gray-500'
                                }`}>
                                  {CHAINS[project.chainId as keyof typeof CHAINS]?.name || `Chain ${project.chainId}`}
                                </span>
                              </div>
                              <div className={`flex items-center gap-2 mt-1 text-xs ${
                                theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                              }`}>
                                <span>{formatVolume(project.volumeUsd)} raised</span>
                                <span>·</span>
                                <span>{project.paymentsCount || 0} payments</span>
                              </div>
                            </div>
                          </div>
                        </button>

                        {/* Supporters list (expanded) */}
                        {isExpanded && (
                          <div className={`ml-8 border-l ${
                            theme === 'dark' ? 'border-white/10' : 'border-gray-200'
                          }`}>
                            {isLoadingSupporters ? (
                              <div className={`px-4 py-2 text-xs ${
                                theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                              }`}>
                                {t('ui.loading', 'Loading...')}
                              </div>
                            ) : supporters.length === 0 ? (
                              <div className={`px-4 py-2 text-xs ${
                                theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                              }`}>
                                {t('projects.noSupporters', 'No conversations yet')}
                              </div>
                            ) : (
                              supporters.map((conv) => (
                                <button
                                  key={conv.id}
                                  onClick={() => handleSelectConversation(conv)}
                                  className={`w-full px-4 py-2 text-left transition-colors ${
                                    conv.chatId === currentChatId
                                      ? theme === 'dark'
                                        ? 'bg-white/10'
                                        : 'bg-gray-100'
                                      : theme === 'dark'
                                        ? 'hover:bg-white/5'
                                        : 'hover:bg-gray-50'
                                  }`}
                                >
                                  <div className="flex items-center justify-between">
                                    <span className={`text-xs font-medium ${
                                      theme === 'dark' ? 'text-gray-300' : 'text-gray-600'
                                    }`}>
                                      {formatAddress(conv.supporterAddress)}
                                    </span>
                                    <span className={`text-xs ${
                                      theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                                    }`}>
                                      {formatWei(conv.totalPaidWei)} ETH
                                    </span>
                                  </div>
                                  {conv.latestMessage && (
                                    <div className={`text-xs truncate mt-0.5 ${
                                      theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                                    }`}>
                                      {conv.latestMessage.content}
                                    </div>
                                  )}
                                </button>
                              ))
                            )}
                          </div>
                        )}
                      </div>
                    )
                  })}
                </div>
              )}
            </>
          )}

          {/* Payments Tab (Supporter view) */}
          {activeTab === 'payments' && (
            <>
              {isWalletAccessLoading ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('ui.loading', 'Loading...')}
                  </div>
                </div>
              ) : !hasWalletAccess ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('wallet.connectToSeePayments', 'Connect wallet to see your payments')}
                  </div>
                  <button
                    onClick={() => window.dispatchEvent(new CustomEvent('juice:open-wallet-panel'))}
                    className="mt-2 text-sm text-juice-orange hover:underline"
                  >
                    {t('wallet.connect', 'Connect Wallet')}
                  </button>
                </div>
              ) : paymentsLoading ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('ui.loading', 'Loading...')}
                  </div>
                </div>
              ) : supporterConversations.length === 0 ? (
                <div className="p-4 text-center">
                  <div className={`text-sm ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
                    {t('payments.noConversations', 'No payment conversations yet')}
                  </div>
                  <p className={`mt-1 text-xs ${theme === 'dark' ? 'text-gray-600' : 'text-gray-400'}`}>
                    {t('payments.hint', 'Pay a project to start a conversation with them')}
                  </p>
                </div>
              ) : (
                <div className="py-2">
                  {supporterConversations.map((conv) => (
                    <button
                      key={conv.id}
                      onClick={() => handleSelectConversation(conv)}
                      className={`w-full px-4 py-3 text-left transition-colors ${
                        conv.chatId === currentChatId
                          ? theme === 'dark'
                            ? 'bg-white/10 border-l-2 border-juice-orange'
                            : 'bg-gray-100 border-l-2 border-juice-orange'
                          : theme === 'dark'
                            ? 'hover:bg-white/5'
                            : 'hover:bg-gray-50'
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        {/* Project placeholder icon */}
                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${
                          theme === 'dark' ? 'bg-white/10' : 'bg-gray-100'
                        }`}>
                          <span className={`text-sm font-medium ${
                            theme === 'dark' ? 'text-gray-400' : 'text-gray-500'
                          }`}>
                            #{conv.projectId}
                          </span>
                        </div>

                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between gap-2">
                            <span className={`text-sm font-medium truncate ${
                              theme === 'dark' ? 'text-gray-200' : 'text-gray-700'
                            }`}>
                              {conv.projectName || `Project #${conv.projectId}`}
                            </span>
                            <span className={`text-xs shrink-0 ${
                              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                            }`}>
                              {formatTimeAgo(conv.updatedAt)}
                            </span>
                          </div>
                          <div className={`flex items-center gap-2 mt-1 text-xs ${
                            theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                          }`}>
                            <span>{formatWei(conv.totalPaidWei)} ETH paid</span>
                            <span>·</span>
                            <span>{conv.paymentCount} payment{conv.paymentCount !== 1 ? 's' : ''}</span>
                          </div>
                          {conv.latestMessage && (
                            <div className={`text-xs truncate mt-0.5 ${
                              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                            }`}>
                              {conv.latestMessage.content}
                            </div>
                          )}
                        </div>
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </>
  )
}
