import { useState, useRef, useEffect, useCallback, useMemo } from 'react'
import { createPortal } from 'react-dom'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useAccount } from 'wagmi'
import { useChatStore, useThemeStore } from '../../stores'
import type { Chat, ChatFolder, ChatMember } from '../../stores/chatStore'
import ParticipantAvatars, { getEmojiFromAddress } from './ParticipantAvatars'
import { getWalletSession } from '../../services/siwe'
import { getSessionId } from '../../services/session'
import {
  pinChat,
  moveChatToFolder,
  renameChat,
  fetchFolders,
  fetchMyChats,
  createFolder,
  updateFolderDetails,
  deleteFolder as deleteFolderApi,
  pinFolder,
  deleteChat as deleteChatApi,
} from '../../services/chat'
import { fetchProjectsByOwner, type Project } from '../../services/bendystraw'
import { useManagedWallet } from '../../hooks'
import { resolveIpfsUri } from '../../utils/ipfs'
import { CHAINS } from '../../constants'
import {
  getOwnerConversations,
  getSupporterConversations,
  type ProjectConversation,
} from '../../api/projectConversations'

type DashboardTab = 'chats' | 'projects' | 'payments'

function formatTimeAgo(timestamp: string): string {
  const now = Date.now()
  const time = new Date(timestamp).getTime()
  const diff = now - time
  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return 'just now'
  if (minutes < 60) return `${minutes}m ago`
  if (hours < 24) return `${hours}h ago`
  if (days < 7) return `${days}d ago`
  return new Date(timestamp).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

function getChatDisplayTitle(chat: Chat): string {
  if (chat.autoGeneratedTitle && isGenericName(chat.name)) {
    return chat.autoGeneratedTitle
  }
  return chat.name || 'Untitled'
}

function getChatSummary(chat: Chat): string {
  // Use description if available
  if (chat.description) {
    return chat.description
  }

  const messages = chat.messages || []
  const messageCount = messages.length
  const userMessages = messages.filter(m => m.role === 'user')
  const aiMessages = messages.filter(m => m.role === 'assistant')

  // Check for abandoned/throwaway chats
  if (messageCount === 0) {
    return 'Empty conversation'
  }

  if (messageCount === 1 && userMessages.length === 1) {
    const content = userMessages[0].content.trim()
    if (content.length < 20) {
      return 'Just getting started...'
    }
    return 'Waiting for a response'
  }

  if (messageCount <= 2 && aiMessages.length === 1) {
    const aiContent = aiMessages[0].content.toLowerCase()
    if (aiContent.includes('help you') && aiContent.includes('gather') || aiContent.includes('let me')) {
      return 'Project setup in progress'
    }
  }

  // Check if it looks abandoned (short exchange, no real substance)
  if (messageCount <= 3) {
    const totalLength = messages.reduce((sum, m) => sum + m.content.length, 0)
    if (totalLength < 200) {
      return 'Not much in this one'
    }
  }

  // Try to extract topic/context from the conversation
  const allContent = messages.map(m => m.content).join(' ').toLowerCase()

  // Detect common themes
  if (allContent.includes('project') && (allContent.includes('launch') || allContent.includes('create'))) {
    if (allContent.includes('fund') || allContent.includes('treasury')) {
      return 'Setting up project funding'
    }
    return 'Planning a new project'
  }

  if (allContent.includes('swap') || allContent.includes('trade') || allContent.includes('exchange')) {
    return 'Token swap discussion'
  }

  if (allContent.includes('pay') || allContent.includes('send') || allContent.includes('transfer')) {
    return 'Payment or transfer'
  }

  if (allContent.includes('nft') || allContent.includes('mint')) {
    return 'NFT-related discussion'
  }

  if (allContent.includes('help') || allContent.includes('how do') || allContent.includes('what is')) {
    return 'Getting help with something'
  }

  // Fallback: summarize based on message count and engagement
  if (messageCount > 10) {
    return `Active conversation with ${messageCount} messages`
  }

  if (messageCount > 5) {
    return 'Ongoing discussion'
  }

  // Last resort: brief excerpt from first user message
  if (userMessages.length > 0) {
    const firstQ = userMessages[0].content.replace(/\n/g, ' ').trim()
    if (firstQ.length > 60) {
      return firstQ.slice(0, 57) + '...'
    }
    return firstQ
  }

  return 'Brief exchange'
}

function isGenericName(name: string | null | undefined): boolean {
  if (!name) return true
  const genericPatterns = [
    /^new chat$/i,
    /^untitled$/i,
    /^chat$/i,
    /^conversation$/i,
    /^\d{4}-\d{2}-\d{2}/,
    /^chat #?\d+$/i,
  ]
  return genericPatterns.some((pattern) => pattern.test(name.trim()))
}

// Bookmark icon component (for pinning)
function PinIcon({ filled, className }: { filled?: boolean; className?: string }) {
  return filled ? (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
    </svg>
  ) : (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
      <path d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// Folder icon component
function FolderIcon({ open, className }: { open?: boolean; className?: string }) {
  return open ? (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 19a2 2 0 01-2-2V7a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1M5 19h14a2 2 0 002-2v-5a2 2 0 00-2-2H9a2 2 0 00-2 2v5a2 2 0 01-2 2z" />
    </svg>
  ) : (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
    </svg>
  )
}

interface ContextMenuProps {
  x: number
  y: number
  theme: string
  onClose: () => void
  onPin: () => void
  onUnpin: () => void
  onRename: () => void
  onMoveToFolder: (folderId: string | null) => void
  onDelete: () => void
  isPinned: boolean
  folders: ChatFolder[]
  currentFolderId?: string
  isFolder?: boolean
}

function ContextMenu({
  x,
  y,
  theme,
  onClose,
  onPin,
  onUnpin,
  onRename,
  onMoveToFolder,
  onDelete,
  isPinned,
  folders,
  currentFolderId,
  isFolder,
}: ContextMenuProps) {
  const availableFolders = folders.filter(f => f.id !== currentFolderId)

  return (
    <>
      {/* Backdrop - catches clicks outside context menu */}
      <div
        className="fixed inset-0 z-[49]"
        onClick={onClose}
      />
      <div
        className={`fixed z-50 shadow-xl py-1 min-w-40 ${
          theme === 'dark' ? 'bg-juice-dark border border-white/20' : 'bg-white border border-gray-200'
        }`}
        style={{ left: x, top: y }}
        onClick={(e) => e.stopPropagation()}
      >
      {/* Pin/Unpin */}
      <button
        onClick={isPinned ? onUnpin : onPin}
        className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
          theme === 'dark'
            ? 'text-gray-300 hover:bg-gray-700'
            : 'text-gray-700 hover:bg-gray-100'
        }`}
      >
        <PinIcon filled={isPinned} className="w-4 h-4" />
        {isPinned ? 'Unpin' : 'Pin'}
      </button>

      {/* Rename */}
      <button
        onClick={onRename}
        className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
          theme === 'dark'
            ? 'text-gray-300 hover:bg-gray-700'
            : 'text-gray-700 hover:bg-gray-100'
        }`}
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
        </svg>
        Rename
      </button>

      {/* Move to folder (only for chats) */}
      {!isFolder && (
        <>
          <div className={`border-t my-1 ${theme === 'dark' ? 'border-gray-700' : 'border-gray-200'}`} />
          <div className={`px-3 py-1 text-xs font-medium ${
            theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
          }`}>
            Move to...
          </div>
          {currentFolderId && (
            <button
              onClick={() => onMoveToFolder(null)}
              className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
                theme === 'dark'
                  ? 'text-gray-300 hover:bg-gray-700'
                  : 'text-gray-700 hover:bg-gray-100'
              }`}
            >
              <span className="w-4" />
              No folder
            </button>
          )}
          {availableFolders.map(folder => (
            <button
              key={folder.id}
              onClick={() => onMoveToFolder(folder.id)}
              className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
                theme === 'dark'
                  ? 'text-gray-300 hover:bg-gray-700'
                  : 'text-gray-700 hover:bg-gray-100'
              }`}
            >
              <FolderIcon className="w-4 h-4" />
              {folder.name}
            </button>
          ))}
        </>
      )}

      {/* Delete */}
      <div className={`border-t my-1 ${theme === 'dark' ? 'border-gray-700' : 'border-gray-200'}`} />
      <button
        onClick={onDelete}
        className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
          theme === 'dark'
            ? 'text-red-400 hover:bg-gray-700'
            : 'text-red-600 hover:bg-gray-100'
        }`}
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
        Delete
      </button>
    </div>
    </>
  )
}

interface RenameModalProps {
  isOpen: boolean
  currentName: string
  onClose: () => void
  onSave: (newName: string) => void
  theme: string
}

function RenameModal({ isOpen, currentName, onClose, onSave, theme }: RenameModalProps) {
  const [name, setName] = useState(currentName)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (isOpen) {
      setName(currentName)
      setTimeout(() => inputRef.current?.select(), 0)
    }
  }, [isOpen, currentName])

  if (!isOpen) return null

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (name.trim()) {
      onSave(name.trim())
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={onClose}>
      <div
        className={`p-4 min-w-72 border shadow-xl ${
          theme === 'dark' ? 'bg-juice-dark border-white/20' : 'bg-white border-gray-200'
        }`}
        onClick={(e) => e.stopPropagation()}
      >
        <h3 className={`text-sm font-medium mb-3 ${
          theme === 'dark' ? 'text-gray-200' : 'text-gray-800'
        }`}>
          Rename
        </h3>
        <form onSubmit={handleSubmit}>
          <input
            ref={inputRef}
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            className={`w-full px-4 py-2.5 text-sm border ${
              theme === 'dark'
                ? 'bg-juice-dark-lighter border-white/10 text-white focus:border-white/30'
                : 'bg-white border-gray-300 text-gray-900 focus:border-gray-400'
            } focus:outline-none`}
            autoFocus
          />
          <div className="flex justify-end gap-2 mt-3">
            <button
              type="button"
              onClick={onClose}
              className={`px-3 py-1.5 text-sm transition-colors ${
                theme === 'dark'
                  ? 'text-gray-300 hover:text-white hover:bg-white/10'
                  : 'text-gray-600 hover:text-gray-900 hover:bg-gray-100'
              }`}
            >
              Cancel
            </button>
            <button
              type="submit"
              className={`px-3 py-1.5 text-sm font-medium transition-colors border ${
                theme === 'dark'
                  ? 'border-green-500 text-green-500 hover:bg-green-500/10'
                  : 'border-green-600 text-green-600 hover:bg-green-600/10'
              }`}
            >
              Save
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

const PAGE_SIZE = 10

export default function ConversationHistory() {
  const { theme } = useThemeStore()
  const { t } = useTranslation()
  const navigate = useNavigate()
  const {
    chats,
    folders,
    activeChatId,
    setActiveChat,
    removeChat,
    updateChat,
    updateMember,
    setChats,
    setFolders,
    addFolder,
    updateFolder,
    removeFolder,
    getPinnedFolders,
    getChatsInFolder,
    getSubfolders,
  } = useChatStore()

  // Get current user address for permission checks
  const currentUserAddress = useMemo(() => {
    const walletSession = getWalletSession()
    const sessionId = getSessionId()
    return walletSession?.address ||
      `0x${sessionId.replace(/[^a-f0-9]/gi, '').slice(0, 40).padStart(40, '0')}`
  }, [])

  // Find current user's member in a chat
  const getCurrentUserMember = useCallback((chat: Chat): ChatMember | undefined => {
    return chat.members?.find(m =>
      m.address?.toLowerCase() === currentUserAddress.toLowerCase()
    )
  }, [currentUserAddress])

  // Handle member permission updates
  const handleMemberUpdated = useCallback((chatId: string, updatedMember: ChatMember) => {
    updateMember(chatId, updatedMember.address, updatedMember)
  }, [updateMember])

  const [contextMenu, setContextMenu] = useState<{
    type: 'chat' | 'folder'
    id: string
    x: number
    y: number
  } | null>(null)
  const [renameModal, setRenameModal] = useState<{
    type: 'chat' | 'folder'
    id: string
    currentName: string
  } | null>(null)
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set())
  const [folderPopover, setFolderPopover] = useState<{ top: number; left: number; above: boolean } | null>(null)
  const [newFolderName, setNewFolderName] = useState('')
  const folderPopoverRef = useRef<HTMLDivElement>(null)
  const [cardMenu, setCardMenu] = useState<{ chatId: string; x: number; y: number } | null>(null)
  const [moveSubmenu, setMoveSubmenu] = useState(false)
  const [folderMenu, setFolderMenu] = useState<{ folderId: string; x: number; y: number } | null>(null)
  const [folderChatMenu, setFolderChatMenu] = useState<{ chatId: string; folderId: string; x: number; y: number } | null>(null)

  // Tab state
  const [activeTab, setActiveTab] = useState<DashboardTab>('chats')

  // Pagination state
  const [totalChats, setTotalChats] = useState(0)
  const [isLoading, setIsLoading] = useState(false)
  const [hasMore, setHasMore] = useState(true)
  const loadMoreRef = useRef<HTMLDivElement>(null)

  // Projects tab state
  const { address: wagmiAddress, isConnected: wagmiConnected } = useAccount()
  const { address: managedAddress, isManagedMode } = useManagedWallet()
  const hasWalletAccess = wagmiConnected || isManagedMode
  const [ownedProjects, setOwnedProjects] = useState<Project[]>([])
  const [projectsLoading, setProjectsLoading] = useState(false)
  const [projectsLoaded, setProjectsLoaded] = useState(false)
  const projectsLoadingRef = useRef(false)

  // Payments tab state
  const [supporterConversations, setSupporterConversations] = useState<ProjectConversation[]>([])
  const [paymentsLoading, setPaymentsLoading] = useState(false)
  const [paymentsLoaded, setPaymentsLoaded] = useState(false)

  // Load chats with pagination
  const loadChats = useCallback(async (offset: number, append: boolean = false) => {
    if (isLoading) return
    setIsLoading(true)
    try {
      const { chats: newChats, total } = await fetchMyChats({ limit: PAGE_SIZE, offset })
      setTotalChats(total)
      setHasMore(offset + newChats.length < total)

      // Merge API data with locally cached messages/members
      const existingChatsMap = new Map(chats.map(c => [c.id, c]))
      const mergedChats = newChats.map(apiChat => {
        const existing = existingChatsMap.get(apiChat.id)
        if (existing) {
          // Preserve locally cached messages and members
          return { ...apiChat, messages: existing.messages, members: existing.members }
        }
        return apiChat
      })

      if (append) {
        // Append to existing chats, avoiding duplicates
        const newIds = new Set(mergedChats.map(c => c.id))
        const existingNotInNew = chats.filter(c => !newIds.has(c.id))
        setChats([...existingNotInNew, ...mergedChats])
      } else {
        setChats(mergedChats)
      }
    } catch (error) {
      console.error('Failed to load chats:', error)
    } finally {
      setIsLoading(false)
    }
  }, [isLoading, setChats, chats])

  // Load owned projects
  const loadProjects = useCallback(async () => {
    if (projectsLoadingRef.current) return
    const addresses = [
      ...(managedAddress ? [managedAddress] : []),
      ...(wagmiAddress ? [wagmiAddress] : []),
    ].filter((addr, i, arr) => arr.indexOf(addr) === i)
    if (addresses.length === 0) return

    projectsLoadingRef.current = true
    setProjectsLoading(true)
    try {
      const results = await Promise.all(addresses.map(addr => fetchProjectsByOwner(addr)))
      const seen = new Set<string>()
      const merged: Project[] = []
      for (const projects of results) {
        for (const p of projects) {
          const key = `${p.projectId}-${p.chainId}`
          if (!seen.has(key)) {
            seen.add(key)
            merged.push(p)
          }
        }
      }
      setOwnedProjects(merged)
      setProjectsLoaded(true)
    } catch (error) {
      console.error('Failed to load projects:', error)
    } finally {
      projectsLoadingRef.current = false
      setProjectsLoading(false)
    }
  }, [managedAddress, wagmiAddress])

  // Load supporter conversations (payments)
  const loadPayments = useCallback(async () => {
    if (paymentsLoading) return

    setPaymentsLoading(true)
    try {
      const result = await getSupporterConversations()
      setSupporterConversations(result.conversations)
      setPaymentsLoaded(true)
    } catch (error) {
      console.error('Failed to load payments:', error)
    } finally {
      setPaymentsLoading(false)
    }
  }, [paymentsLoading])

  // Load initial data
  useEffect(() => {
    fetchFolders().then(setFolders).catch(console.error)
    loadChats(0)
  }, [setFolders]) // eslint-disable-line react-hooks/exhaustive-deps

  // Load projects/payments when tab changes
  useEffect(() => {
    if (activeTab === 'projects' && hasWalletAccess && !projectsLoaded) {
      loadProjects()
    }
    if (activeTab === 'payments' && hasWalletAccess && !paymentsLoaded) {
      loadPayments()
    }
  }, [activeTab, hasWalletAccess, projectsLoaded, paymentsLoaded, loadProjects, loadPayments])

  // Intersection observer for infinite scroll
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMore && !isLoading) {
          loadChats(chats.length, true)
        }
      },
      { threshold: 0.1 }
    )

    if (loadMoreRef.current) {
      observer.observe(loadMoreRef.current)
    }

    return () => observer.disconnect()
  }, [hasMore, isLoading, chats.length, loadChats])

  const closeFolderPopover = () => {
    setFolderPopover(null)
    setNewFolderName('')
  }

  // Get organized data
  const pinnedFolders = getPinnedFolders()
  const rootFolders = getSubfolders(null)
  const rootChats = getChatsInFolder(null)

  if (chats.length === 0 && folders.length === 0 && !isLoading) return null

  const handleSelectChat = (id: string) => {
    setActiveChat(id)
    navigate(`/chat/${id}`)
  }

  const handleContextMenu = (e: React.MouseEvent, type: 'chat' | 'folder', id: string) => {
    e.preventDefault()
    e.stopPropagation()
    setContextMenu({ type, id, x: e.clientX, y: e.clientY })
  }

  const handleCloseContextMenu = () => setContextMenu(null)

  const handlePin = async () => {
    if (!contextMenu) return
    try {
      if (contextMenu.type === 'chat') {
        const updated = await pinChat(contextMenu.id, true)
        updateChat(contextMenu.id, { isPinned: updated.isPinned, pinOrder: updated.pinOrder })
      } else {
        const updated = await pinFolder(contextMenu.id, true)
        updateFolder(contextMenu.id, { isPinned: updated.isPinned, pinOrder: updated.pinOrder })
      }
    } catch (error) {
      console.error('Failed to pin:', error)
    }
    setContextMenu(null)
  }

  const handleUnpin = async () => {
    if (!contextMenu) return
    try {
      if (contextMenu.type === 'chat') {
        const updated = await pinChat(contextMenu.id, false)
        updateChat(contextMenu.id, { isPinned: updated.isPinned, pinOrder: undefined })
      } else {
        const updated = await pinFolder(contextMenu.id, false)
        updateFolder(contextMenu.id, { isPinned: updated.isPinned, pinOrder: undefined })
      }
    } catch (error) {
      console.error('Failed to unpin:', error)
    }
    setContextMenu(null)
  }

  const handleOpenRename = () => {
    if (!contextMenu) return
    if (contextMenu.type === 'chat') {
      const chat = chats.find(c => c.id === contextMenu.id)
      if (chat) {
        setRenameModal({ type: 'chat', id: chat.id, currentName: getChatDisplayTitle(chat) })
      }
    } else {
      const folder = folders.find(f => f.id === contextMenu.id)
      if (folder) {
        setRenameModal({ type: 'folder', id: folder.id, currentName: folder.name })
      }
    }
    setContextMenu(null)
  }

  const handleRename = async (newName: string) => {
    if (!renameModal) return
    try {
      if (renameModal.type === 'chat') {
        const updated = await renameChat(renameModal.id, newName)
        updateChat(renameModal.id, { name: updated.name })
      } else {
        const updated = await updateFolderDetails(renameModal.id, { name: newName })
        updateFolder(renameModal.id, { name: updated.name })
      }
    } catch (error) {
      console.error('Failed to rename:', error)
    }
    setRenameModal(null)
  }

  const handleMoveToFolder = async (folderId: string | null) => {
    if (!contextMenu || contextMenu.type !== 'chat') return
    try {
      const updated = await moveChatToFolder(contextMenu.id, folderId)
      updateChat(contextMenu.id, { folderId: updated.folderId })
    } catch (error) {
      console.error('Failed to move chat:', error)
    }
    setContextMenu(null)
  }

  const handleDelete = async () => {
    if (!contextMenu) return
    if (contextMenu.type === 'chat') {
      try {
        await deleteChatApi(contextMenu.id)
        removeChat(contextMenu.id)
      } catch (error) {
        console.error('Failed to delete chat:', error)
      }
    } else {
      try {
        await deleteFolderApi(contextMenu.id)
        removeFolder(contextMenu.id)
      } catch (error) {
        console.error('Failed to delete folder:', error)
      }
    }
    setContextMenu(null)
  }

  const toggleFolder = (folderId: string) => {
    setExpandedFolders(prev => {
      const next = new Set(prev)
      if (next.has(folderId)) {
        next.delete(folderId)
      } else {
        next.add(folderId)
      }
      return next
    })
  }

  const handleCreateFolder = async () => {
    if (!newFolderName.trim()) return
    try {
      const folder = await createFolder(newFolderName.trim())
      addFolder(folder)
      setNewFolderName('')
      setFolderPopover(null)
    } catch (error) {
      console.error('Failed to create folder:', error)
    }
  }

  const openFolderPopover = (e: React.MouseEvent<HTMLButtonElement>) => {
    const rect = e.currentTarget.getBoundingClientRect()
    // If button is in bottom half of page, show popover above it
    const inBottomHalf = rect.top > window.innerHeight / 2
    setFolderPopover({
      top: inBottomHalf ? rect.top : rect.bottom,
      left: rect.left,
      above: inBottomHalf,
    })
  }

  const getContextItem = () => {
    if (!contextMenu) return null
    if (contextMenu.type === 'chat') {
      return chats.find(c => c.id === contextMenu.id)
    }
    return folders.find(f => f.id === contextMenu.id)
  }

  const contextItem = getContextItem()

  // Render a chat card for grid layout
  const renderChatCard = (chat: Chat) => {
    const summary = getChatSummary(chat)
    const isMenuOpen = cardMenu?.chatId === chat.id

    return (
      <div
        key={chat.id}
        onClick={() => handleSelectChat(chat.id)}
        onContextMenu={(e) => handleContextMenu(e, 'chat', chat.id)}
        className={`group relative p-4 border cursor-pointer transition-colors flex flex-col ${
          chat.id === activeChatId
            ? theme === 'dark'
              ? 'bg-white/10 border-white/30 text-white'
              : 'bg-gray-100 border-gray-300 text-gray-900'
            : theme === 'dark'
              ? 'bg-white/5 border-white/10 hover:bg-white/[0.08] hover:border-white/20'
              : 'bg-gray-50 border-gray-200 hover:bg-gray-100 hover:border-gray-300'
        }`}
      >
        {/* Time - top right */}
        <span className={`absolute top-3 right-3 text-xs ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
          {formatTimeAgo(chat.updatedAt)}
        </span>

        {/* Pin indicator - top left */}
        {chat.isPinned && (
          <PinIcon filled className={`absolute top-3 left-3 w-3 h-3 ${
            theme === 'dark' ? 'text-purple-400' : 'text-purple-600'
          }`} />
        )}

        {/* Title */}
        <h3 className={`text-sm font-medium mb-1 pr-16 ${chat.isPinned ? 'pl-5' : ''} line-clamp-2 ${
          theme === 'dark' ? 'text-gray-100' : 'text-gray-800'
        }`}>
          {getChatDisplayTitle(chat)}
        </h3>

        {/* Summary */}
        {summary && (
          <p className={`text-xs leading-relaxed line-clamp-3 ${
            theme === 'dark' ? 'text-gray-400' : 'text-gray-500'
          }`}>
            {summary}
          </p>
        )}

        {/* Footer with participants and three-dot menu */}
        <div className="flex items-center justify-between mt-auto pt-3">
          {/* Participant avatars with username */}
          {chat.members && chat.members.length > 0 ? (
            <div className="flex items-center gap-1 min-w-0 flex-1 mr-2">
              {/* Skip first member in avatars since they're shown separately */}
              {chat.members.length > 1 && (
                <ParticipantAvatars
                  members={chat.members.slice(1)}
                  onlineMembers={chat.onlineMembers}
                  maxVisible={4}
                  size="sm"
                  chatId={chat.id}
                  currentUserMember={getCurrentUserMember(chat)}
                  onMemberUpdated={(member) => handleMemberUpdated(chat.id, member)}
                />
              )}
              {/* Show first member's Juicy ID (emoji + username) - hide if only one member (you) */}
              {chat.members.length > 1 && (
                <div className={`flex items-center gap-1.5 px-2 py-1 rounded-md border ${
                  theme === 'dark'
                    ? 'border-white/15 bg-juice-dark'
                    : 'border-gray-200 bg-white'
                }`}>
                  <span className="text-sm shrink-0">
                    {chat.members[0].customEmoji || getEmojiFromAddress(chat.members[0].address)}
                  </span>
                  {chat.members[0].displayName && (
                    <span className={`text-xs truncate max-w-[100px] ${
                      theme === 'dark' ? 'text-gray-300' : 'text-gray-600'
                    }`}>
                      {chat.members[0].displayName}
                    </span>
                  )}
                </div>
              )}
            </div>
          ) : (
            <div />
          )}
          {/* Menu button */}
          <button
            onClick={(e) => {
              e.stopPropagation()
              const rect = e.currentTarget.getBoundingClientRect()
              setCardMenu({ chatId: chat.id, x: rect.right, y: rect.bottom })
              setMoveSubmenu(false)
            }}
            className={`p-1 rounded transition-opacity ${
              isMenuOpen
                ? theme === 'dark' ? 'text-white' : 'text-gray-700'
                : `opacity-0 group-hover:opacity-100 ${theme === 'dark' ? 'text-gray-500 hover:text-white' : 'text-gray-400 hover:text-gray-700'}`
            }`}
          >
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
              <circle cx="5" cy="12" r="2" />
              <circle cx="12" cy="12" r="2" />
              <circle cx="19" cy="12" r="2" />
            </svg>
          </button>
        </div>
      </div>
    )
  }

  // Render a chat item for list layout (used inside folders)
  const renderChat = (chat: Chat, indent = 0) => (
    <div
      key={chat.id}
      onClick={() => handleSelectChat(chat.id)}
      onContextMenu={(e) => handleContextMenu(e, 'chat', chat.id)}
      style={{ paddingLeft: indent > 0 ? `${indent * 16}px` : undefined }}
      className={`group flex items-center justify-between py-1.5 pr-2 rounded cursor-pointer transition-colors ${
        chat.id === activeChatId
          ? theme === 'dark'
            ? 'bg-white/5 text-white'
            : 'bg-gray-100 text-gray-900'
          : theme === 'dark'
            ? 'text-gray-400 hover:text-gray-200 hover:bg-white/5'
            : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
      }`}
    >
      <div className="flex items-center gap-2 flex-1 min-w-0">
        {chat.isPinned && (
          <PinIcon filled className={`w-3 h-3 shrink-0 ${
            theme === 'dark' ? 'text-purple-400' : 'text-purple-600'
          }`} />
        )}
        <div className="flex-1 min-w-0">
          <div className={`text-sm truncate ${
            chat.id === activeChatId ? '' : theme === 'dark' ? 'text-gray-300' : 'text-gray-700'
          }`}>
            {getChatDisplayTitle(chat)}
          </div>
          <div className={`text-xs ${theme === 'dark' ? 'text-gray-600' : 'text-gray-400'}`}>
            {formatTimeAgo(chat.updatedAt)}
          </div>
        </div>
      </div>
      {/* Trash button - visible on hover */}
      <button
        onClick={async (e) => {
          e.stopPropagation()
          try {
            await deleteChatApi(chat.id)
            removeChat(chat.id)
          } catch (error) {
            console.error('Failed to delete chat:', error)
          }
        }}
        className={`shrink-0 p-1 opacity-0 group-hover:opacity-100 transition-opacity ${
          theme === 'dark'
            ? 'text-gray-600 hover:text-red-400'
            : 'text-gray-300 hover:text-red-500'
        }`}
        title="Delete"
      >
        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      </button>
    </div>
  )

  // Render a folder card for grid layout (dashed border style)
  const renderFolderCard = (folder: ChatFolder) => {
    const folderChats = getChatsInFolder(folder.id)
    const isExpanded = expandedFolders.has(folder.id)
    const isMenuOpen = folderMenu?.folderId === folder.id

    return (
      <div
        key={folder.id}
        onClick={() => toggleFolder(folder.id)}
        onContextMenu={(e) => handleContextMenu(e, 'folder', folder.id)}
        className={`group relative p-4 border-2 border-dashed cursor-pointer transition-colors flex flex-col ${
          theme === 'dark'
            ? 'border-white/20 hover:border-white/40 hover:bg-white/5'
            : 'border-gray-300 hover:border-gray-400 hover:bg-gray-50'
        }`}
      >
        {/* Chat count - top right */}
        <span className={`absolute top-3 right-3 text-xs ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
          {folderChats.length} {folderChats.length === 1 ? 'chat' : 'chats'}
        </span>

        {/* Pin indicator - top left */}
        {folder.isPinned && (
          <PinIcon filled className={`absolute top-3 left-3 w-3 h-3 ${
            theme === 'dark' ? 'text-purple-400' : 'text-purple-600'
          }`} />
        )}

        {/* Folder icon and title */}
        <div className={`flex items-center gap-2 mb-1 ${folder.isPinned ? 'pl-5' : ''}`}>
          <FolderIcon open={isExpanded} className={`w-5 h-5 shrink-0 ${
            theme === 'dark' ? 'text-gray-400' : 'text-gray-500'
          }`} />
          <h3 className={`text-sm font-medium pr-16 line-clamp-2 ${
            theme === 'dark' ? 'text-gray-100' : 'text-gray-800'
          }`}>
            {folder.name}
          </h3>
        </div>

        {/* Collapsed: show inline preview text */}
        {!isExpanded && folderChats.length > 0 && (
          <p className={`text-xs mt-1 line-clamp-1 ${
            theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
          }`}>
            {folderChats.slice(0, 3).map(c => getChatDisplayTitle(c)).join(', ')}
            {folderChats.length > 3 ? '...' : ''}
          </p>
        )}

        {/* Expanded: show full list with actions */}
        {isExpanded && folderChats.length > 0 && (
          <div className={`mt-2 pt-2 border-t space-y-0.5 ${
            theme === 'dark' ? 'border-white/10' : 'border-gray-200'
          }`}>
            {folderChats.slice(0, 5).map(chat => (
              <div
                key={chat.id}
                className={`group/item flex items-center justify-between py-2 px-1 rounded ${
                  theme === 'dark'
                    ? 'hover:bg-white/10'
                    : 'hover:bg-gray-100'
                }`}
              >
                <span
                  onClick={(e) => {
                    e.stopPropagation()
                    handleSelectChat(chat.id)
                  }}
                  className={`text-xs truncate cursor-pointer flex-1 ${
                    theme === 'dark'
                      ? 'text-gray-400 hover:text-gray-200'
                      : 'text-gray-500 hover:text-gray-700'
                  }`}
                >
                  {getChatDisplayTitle(chat)}
                </span>
                <button
                  onClick={(e) => {
                    e.stopPropagation()
                    const rect = e.currentTarget.getBoundingClientRect()
                    setFolderChatMenu({ chatId: chat.id, folderId: folder.id, x: rect.right, y: rect.bottom })
                  }}
                  className={`shrink-0 p-0.5 opacity-0 group-hover/item:opacity-100 transition-opacity ${
                    theme === 'dark' ? 'text-gray-500 hover:text-white' : 'text-gray-400 hover:text-gray-700'
                  }`}
                >
                  <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 24 24">
                    <circle cx="5" cy="12" r="2" />
                    <circle cx="12" cy="12" r="2" />
                    <circle cx="19" cy="12" r="2" />
                  </svg>
                </button>
              </div>
            ))}
            {folderChats.length > 5 && (
              <div className={`text-xs px-1 ${theme === 'dark' ? 'text-gray-600' : 'text-gray-400'}`}>
                +{folderChats.length - 5} more
              </div>
            )}
          </div>
        )}

        {/* Footer with three-dot menu - only show when expanded */}
        {isExpanded && (
          <div className="flex items-center justify-end mt-auto pt-3">
            <button
              onClick={(e) => {
                e.stopPropagation()
                const rect = e.currentTarget.getBoundingClientRect()
                setFolderMenu({ folderId: folder.id, x: rect.right, y: rect.bottom })
              }}
              className={`p-1 rounded transition-opacity ${
                isMenuOpen
                  ? theme === 'dark' ? 'text-white' : 'text-gray-700'
                  : `opacity-0 group-hover:opacity-100 ${theme === 'dark' ? 'text-gray-500 hover:text-white' : 'text-gray-400 hover:text-gray-700'}`
              }`}
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <circle cx="5" cy="12" r="2" />
                <circle cx="12" cy="12" r="2" />
                <circle cx="19" cy="12" r="2" />
              </svg>
            </button>
          </div>
        )}
      </div>
    )
  }

  // Helper to get chain name
  const getChainName = (chainId: number) => {
    const chain = CHAINS[chainId]
    return chain?.name || `Chain ${chainId}`
  }

  return (
    <div className="px-6 mt-8">
      {/* Tab navigation */}
      <div className={`flex mb-4 border-b ${theme === 'dark' ? 'border-white/10' : 'border-gray-200'}`}>
        <button
          onClick={() => setActiveTab('chats')}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            activeTab === 'chats'
              ? theme === 'dark'
                ? 'text-white border-b-2 border-juice-orange'
                : 'text-gray-900 border-b-2 border-juice-orange'
              : theme === 'dark'
                ? 'text-gray-400 hover:text-gray-200'
                : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          {t('ui.chats', 'Chats')}
        </button>
        <button
          onClick={() => setActiveTab('projects')}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            activeTab === 'projects'
              ? theme === 'dark'
                ? 'text-white border-b-2 border-juice-orange'
                : 'text-gray-900 border-b-2 border-juice-orange'
              : theme === 'dark'
                ? 'text-gray-400 hover:text-gray-200'
                : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          {t('ui.myProjects', 'My Projects')}
        </button>
        <button
          onClick={() => setActiveTab('payments')}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            activeTab === 'payments'
              ? theme === 'dark'
                ? 'text-white border-b-2 border-juice-orange'
                : 'text-gray-900 border-b-2 border-juice-orange'
              : theme === 'dark'
                ? 'text-gray-400 hover:text-gray-200'
                : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          {t('ui.paymentsMade', 'Payments made')}
        </button>
      </div>

      {/* Chats Tab Content */}
      {activeTab === 'chats' && (
        <>
          {/* Header with create folder button on right */}
          <div className="flex items-center justify-between mb-2">
            <span className={`text-xs font-medium ${
              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
            }`}>
              {t('ui.recent', 'Recent')} ({totalChats || chats.length})
            </span>
            <button
              onClick={openFolderPopover}
              className={`text-xs px-2 py-1 border transition-colors ${
                theme === 'dark'
                  ? 'border-white/10 text-gray-400 hover:text-white hover:border-white/20'
                  : 'border-gray-200 text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              {t('ui.newFolder', 'New folder')}
            </button>
          </div>

      {/* Folder creation popover - rendered via portal to escape backdrop-blur containing block */}
      {folderPopover && createPortal(
        <>
          {/* Backdrop - catches clicks outside popover */}
          <div
            className="fixed inset-0 z-[49]"
            onClick={closeFolderPopover}
          />
          <div
            ref={folderPopoverRef}
            className={`fixed z-50 p-3 shadow-xl ${
              theme === 'dark' ? 'bg-juice-dark border border-white/20' : 'bg-white border border-gray-200'
            }`}
            style={{
              left: folderPopover.left,
              ...(folderPopover.above
                ? { bottom: window.innerHeight - folderPopover.top + 4 }
                : { top: folderPopover.top + 4 }),
            }}
          >
            <div className="flex gap-2">
              <input
                type="text"
                value={newFolderName}
                onChange={(e) => setNewFolderName(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') handleCreateFolder()
                  if (e.key === 'Escape') closeFolderPopover()
                }}
                placeholder="Folder name..."
                className={`w-40 px-3 py-1.5 text-sm border ${
                  theme === 'dark'
                    ? 'bg-juice-dark-lighter border-white/10 text-white placeholder-gray-500 focus:border-white/30'
                    : 'bg-white border-gray-300 text-gray-900 placeholder-gray-400 focus:border-gray-400'
                } focus:outline-none`}
                autoFocus
              />
              <button
                onClick={handleCreateFolder}
                className={`px-3 py-1.5 text-sm font-medium transition-colors border ${
                  theme === 'dark'
                    ? 'border-green-500 text-green-500 hover:bg-green-500/10'
                    : 'border-green-600 text-green-600 hover:bg-green-600/10'
                }`}
              >
                Create
              </button>
            </div>
          </div>
        </>,
        document.body
      )}

      {/* Grid - folders and chats together */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {/* Pinned folders first */}
        {pinnedFolders.map(folder => renderFolderCard(folder))}
        {/* Unpinned folders */}
        {rootFolders.filter(f => !f.isPinned).map(folder => renderFolderCard(folder))}
        {/* Then chats */}
        {rootChats.map(chat => renderChatCard(chat))}
      </div>

          {/* Load more trigger */}
          {hasMore && (
            <div
              ref={loadMoreRef}
              className={`py-6 text-center text-xs ${
                theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
              }`}
            >
              {isLoading ? 'Loading...' : ''}
            </div>
          )}
        </>
      )}

      {/* Projects Tab Content */}
      {activeTab === 'projects' && (
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className={`text-xs font-medium ${
              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
            }`}>
              {t('ui.projectsYouOwn', 'Projects you own')} ({ownedProjects.length})
            </span>
          </div>
          {!hasWalletAccess ? (
            <div className={`p-8 text-center ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
              <p className="text-sm">{t('wallet.connectToSeeProjects', 'Connect wallet to see your projects')}</p>
            </div>
          ) : projectsLoading ? (
            <div className={`p-8 text-center ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
              <p className="text-sm">{t('ui.loading', 'Loading...')}</p>
            </div>
          ) : ownedProjects.length === 0 ? (
            <div className={`p-8 text-center ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
              <p className="text-sm">{t('projects.noOwned', "You don't own any projects yet")}</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {ownedProjects.map(project => (
                <div
                  key={project.id}
                  onClick={() => {
                    const chain = CHAINS[project.chainId]
                    if (chain) {
                      // Use simple slug format without hyphens (e.g., opsep instead of op-sep)
                      const urlSlug = chain.slug.replace(/-/g, '')
                      navigate(`/${urlSlug}:${project.projectId}`)
                    }
                  }}
                  className={`group p-4 border cursor-pointer transition-colors ${
                    theme === 'dark'
                      ? 'border-white/10 hover:border-white/20 bg-white/5 hover:bg-white/10'
                      : 'border-gray-200 hover:border-gray-300 bg-gray-50 hover:bg-gray-100'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    {project.logoUri ? (
                      <img
                        src={resolveIpfsUri(project.logoUri) || undefined}
                        alt=""
                        className="w-10 h-10 rounded-full object-cover"
                      />
                    ) : (
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center text-lg ${
                        theme === 'dark' ? 'bg-white/10' : 'bg-gray-200'
                      }`}>
                        🍊
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <h3 className={`font-medium text-sm truncate ${
                        theme === 'dark' ? 'text-white' : 'text-gray-900'
                      }`}>
                        {project.name || `Project #${project.projectId}`}
                      </h3>
                      <p className={`text-xs truncate ${
                        theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                      }`}>
                        {getChainName(project.chainId)} · #{project.projectId}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Payments Tab Content */}
      {activeTab === 'payments' && (
        <div>
          <div className="flex items-center justify-between mb-2">
            <span className={`text-xs font-medium ${
              theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
            }`}>
              {t('ui.projectsYouSupport', 'Projects you support')} ({supporterConversations.length})
            </span>
          </div>
          {!hasWalletAccess ? (
            <div className={`p-8 text-center ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
              <p className="text-sm">{t('wallet.connectToSeePayments', 'Connect wallet to see your payments')}</p>
            </div>
          ) : paymentsLoading ? (
            <div className={`p-8 text-center ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
              <p className="text-sm">{t('ui.loading', 'Loading...')}</p>
            </div>
          ) : supporterConversations.length === 0 ? (
            <div className={`p-8 text-center ${theme === 'dark' ? 'text-gray-500' : 'text-gray-400'}`}>
              <p className="text-sm">{t('payments.noPayments', "You haven't supported any projects yet")}</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {supporterConversations.map(conv => (
                <div
                  key={conv.chatId}
                  onClick={() => navigate(`/chat/${conv.chatId}`)}
                  className={`group p-4 border cursor-pointer transition-colors ${
                    theme === 'dark'
                      ? 'border-white/10 hover:border-white/20 bg-white/5 hover:bg-white/10'
                      : 'border-gray-200 hover:border-gray-300 bg-gray-50 hover:bg-gray-100'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    {conv.projectLogoUri ? (
                      <img
                        src={resolveIpfsUri(conv.projectLogoUri) || undefined}
                        alt=""
                        className="w-10 h-10 rounded-full object-cover"
                      />
                    ) : (
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center text-lg ${
                        theme === 'dark' ? 'bg-white/10' : 'bg-gray-200'
                      }`}>
                        🍊
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <h3 className={`font-medium text-sm truncate ${
                        theme === 'dark' ? 'text-white' : 'text-gray-900'
                      }`}>
                        {conv.projectName || `Project #${conv.projectId}`}
                      </h3>
                      <p className={`text-xs truncate ${
                        theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                      }`}>
                        {getChainName(conv.chainId)} · #{conv.projectId}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Card dropdown menu */}
      {cardMenu && createPortal(
        (() => {
          const menuWidth = 144 // min-w-36 = 9rem = 144px
          const menuHeight = 120 // approximate height
          const submenuWidth = 144
          const padding = 8

          // Calculate ideal position (right-aligned to button)
          let menuLeft = cardMenu.x - menuWidth
          let menuTop = cardMenu.y + 4

          // Clamp horizontal to viewport
          if (menuLeft < padding) menuLeft = padding
          if (menuLeft + menuWidth > window.innerWidth - padding) {
            menuLeft = window.innerWidth - padding - menuWidth
          }

          // Clamp vertical to viewport
          if (menuTop + menuHeight > window.innerHeight - padding) {
            menuTop = cardMenu.y - menuHeight - 4
          }
          if (menuTop < padding) menuTop = padding

          // Decide submenu direction: prefer right, but flip if no space
          const spaceOnRight = window.innerWidth - (menuLeft + menuWidth)
          const spaceOnLeft = menuLeft
          const flipSubmenu = spaceOnRight < submenuWidth + padding && spaceOnLeft > submenuWidth

          // Calculate submenu position with clamping
          let submenuLeft = flipSubmenu ? menuLeft - submenuWidth - 4 : menuLeft + menuWidth + 4
          if (submenuLeft < padding) submenuLeft = padding
          if (submenuLeft + submenuWidth > window.innerWidth - padding) {
            submenuLeft = window.innerWidth - padding - submenuWidth
          }

          return (
        <>
          <div className="fixed inset-0 z-[49]" onClick={() => { setCardMenu(null); setMoveSubmenu(false) }} />
          <div
            className={`fixed z-50 shadow-xl py-1 min-w-36 ${
              theme === 'dark' ? 'bg-juice-dark border border-white/20' : 'bg-white border border-gray-200'
            }`}
            style={{ left: menuLeft, top: menuTop }}
            data-flip-submenu={flipSubmenu}
          >
            {/* Pin/Unpin */}
            <button
              onClick={async () => {
                const chat = chats.find(c => c.id === cardMenu.chatId)
                if (chat) {
                  try {
                    const updated = await pinChat(chat.id, !chat.isPinned)
                    updateChat(chat.id, { isPinned: updated.isPinned, pinOrder: updated.pinOrder })
                  } catch (error) {
                    console.error('Failed to toggle pin:', error)
                  }
                }
                setCardMenu(null)
              }}
              className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
                theme === 'dark' ? 'text-gray-300 hover:bg-gray-700' : 'text-gray-700 hover:bg-gray-100'
              }`}
            >
              <PinIcon filled={chats.find(c => c.id === cardMenu.chatId)?.isPinned} className="w-4 h-4" />
              {chats.find(c => c.id === cardMenu.chatId)?.isPinned ? 'Unpin' : 'Pin'}
            </button>

            {/* Move to folder */}
            <div className="relative">
              <button
                onClick={() => setMoveSubmenu(!moveSubmenu)}
                className={`w-full text-left px-3 py-1.5 text-sm flex items-center justify-between ${
                  theme === 'dark' ? 'text-gray-300 hover:bg-gray-700' : 'text-gray-700 hover:bg-gray-100'
                }`}
              >
                <span className="flex items-center gap-2">
                  <FolderIcon className="w-4 h-4" />
                  Move
                </span>
                <svg className={`w-3 h-3 transition-transform ${flipSubmenu ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </button>

              {/* Move submenu */}
              {moveSubmenu && (
                <div
                  className={`fixed py-1 min-w-36 shadow-xl z-[51] ${
                    theme === 'dark' ? 'bg-juice-dark border border-white/20' : 'bg-white border border-gray-200'
                  }`}
                  style={{
                    top: menuTop + 28, // offset to align with Move button
                    left: submenuLeft,
                  }}
                >
                  {/* No folder option */}
                  {chats.find(c => c.id === cardMenu.chatId)?.folderId && (
                    <button
                      onClick={async () => {
                        try {
                          const updated = await moveChatToFolder(cardMenu.chatId, null)
                          updateChat(cardMenu.chatId, { folderId: updated.folderId })
                        } catch (error) {
                          console.error('Failed to move chat:', error)
                        }
                        setCardMenu(null)
                        setMoveSubmenu(false)
                      }}
                      className={`w-full text-left px-3 py-1.5 text-sm ${
                        theme === 'dark' ? 'text-gray-300 hover:bg-gray-700' : 'text-gray-700 hover:bg-gray-100'
                      }`}
                    >
                      No folder
                    </button>
                  )}
                  {/* Folder options */}
                  {rootFolders.map(folder => (
                    <button
                      key={folder.id}
                      onClick={async () => {
                        try {
                          const updated = await moveChatToFolder(cardMenu.chatId, folder.id)
                          updateChat(cardMenu.chatId, { folderId: updated.folderId })
                        } catch (error) {
                          console.error('Failed to move chat:', error)
                        }
                        setCardMenu(null)
                        setMoveSubmenu(false)
                      }}
                      className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
                        theme === 'dark' ? 'text-gray-300 hover:bg-gray-700' : 'text-gray-700 hover:bg-gray-100'
                      }`}
                    >
                      <FolderIcon className="w-4 h-4" />
                      {folder.name}
                    </button>
                  ))}
                  {rootFolders.length === 0 && (
                    <div className={`px-3 py-1.5 text-sm ${
                      theme === 'dark' ? 'text-gray-500' : 'text-gray-400'
                    }`}>
                      No folders yet
                    </div>
                  )}
                </div>
              )}
            </div>

            <div className={`border-t my-1 ${theme === 'dark' ? 'border-gray-700' : 'border-gray-200'}`} />

            {/* Trash */}
            <button
              onClick={async () => {
                try {
                  await deleteChatApi(cardMenu.chatId)
                  removeChat(cardMenu.chatId)
                } catch (error) {
                  console.error('Failed to delete chat:', error)
                }
                setCardMenu(null)
              }}
              className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
                theme === 'dark' ? 'text-red-400 hover:bg-gray-700' : 'text-red-600 hover:bg-gray-100'
              }`}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
              Trash
            </button>
          </div>
        </>
          )
        })(),
        document.body
      )}

      {/* Folder dropdown menu */}
      {folderMenu && createPortal(
        (() => {
          const folder = folders.find(f => f.id === folderMenu.folderId)
          if (!folder) return null

          const menuWidth = 144
          const menuHeight = 80
          const padding = 8

          let menuLeft = folderMenu.x - menuWidth
          let menuTop = folderMenu.y + 4

          if (menuLeft < padding) menuLeft = padding
          if (menuLeft + menuWidth > window.innerWidth - padding) {
            menuLeft = window.innerWidth - padding - menuWidth
          }
          if (menuTop + menuHeight > window.innerHeight - padding) {
            menuTop = folderMenu.y - menuHeight - 4
          }
          if (menuTop < padding) menuTop = padding

          return (
            <>
              <div className="fixed inset-0 z-[49]" onClick={() => setFolderMenu(null)} />
              <div
                className={`fixed z-50 shadow-xl py-1 min-w-36 ${
                  theme === 'dark' ? 'bg-juice-dark border border-white/20' : 'bg-white border border-gray-200'
                }`}
                style={{ left: menuLeft, top: menuTop }}
              >
                {/* Pin/Unpin */}
                <button
                  onClick={async () => {
                    try {
                      const updated = await pinFolder(folder.id, !folder.isPinned)
                      updateFolder(folder.id, { isPinned: updated.isPinned, pinOrder: updated.pinOrder })
                    } catch (error) {
                      console.error('Failed to toggle pin:', error)
                    }
                    setFolderMenu(null)
                  }}
                  className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
                    theme === 'dark' ? 'text-gray-300 hover:bg-gray-700' : 'text-gray-700 hover:bg-gray-100'
                  }`}
                >
                  <PinIcon filled={folder.isPinned} className="w-4 h-4" />
                  {folder.isPinned ? 'Unpin' : 'Pin'}
                </button>

                <div className={`border-t my-1 ${theme === 'dark' ? 'border-gray-700' : 'border-gray-200'}`} />

                {/* Trash folder */}
                <button
                  onClick={async () => {
                    try {
                      // Move all chats out of folder first (they stay in history)
                      const folderChats = getChatsInFolder(folder.id)
                      for (const chat of folderChats) {
                        const updated = await moveChatToFolder(chat.id, null)
                        updateChat(chat.id, { folderId: updated.folderId })
                      }
                      // Then delete the folder
                      await deleteFolderApi(folder.id)
                      removeFolder(folder.id)
                    } catch (error) {
                      console.error('Failed to delete folder:', error)
                    }
                    setFolderMenu(null)
                  }}
                  className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 ${
                    theme === 'dark' ? 'text-red-400 hover:bg-gray-700' : 'text-red-600 hover:bg-gray-100'
                  }`}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                  Trash
                </button>
              </div>
            </>
          )
        })(),
        document.body
      )}

      {/* Folder chat menu (remove from folder) */}
      {folderChatMenu && createPortal(
        (() => {
          const menuWidth = 160
          const menuHeight = 40
          const padding = 8

          let menuLeft = folderChatMenu.x - menuWidth
          let menuTop = folderChatMenu.y + 4

          if (menuLeft < padding) menuLeft = padding
          if (menuLeft + menuWidth > window.innerWidth - padding) {
            menuLeft = window.innerWidth - padding - menuWidth
          }
          if (menuTop + menuHeight > window.innerHeight - padding) {
            menuTop = folderChatMenu.y - menuHeight - 4
          }
          if (menuTop < padding) menuTop = padding

          return (
            <>
              <div className="fixed inset-0 z-[49]" onClick={() => setFolderChatMenu(null)} />
              <div
                className={`fixed z-50 shadow-xl py-1 ${
                  theme === 'dark' ? 'bg-juice-dark border border-white/20' : 'bg-white border border-gray-200'
                }`}
                style={{ left: menuLeft, top: menuTop }}
              >
                <button
                  onClick={async () => {
                    try {
                      const updated = await moveChatToFolder(folderChatMenu.chatId, null)
                      updateChat(folderChatMenu.chatId, { folderId: updated.folderId })
                    } catch (error) {
                      console.error('Failed to remove from folder:', error)
                    }
                    setFolderChatMenu(null)
                  }}
                  className={`w-full text-left px-3 py-1.5 text-sm flex items-center gap-2 whitespace-nowrap ${
                    theme === 'dark' ? 'text-gray-300 hover:bg-gray-700' : 'text-gray-700 hover:bg-gray-100'
                  }`}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                  </svg>
                  Remove from folder
                </button>
              </div>
            </>
          )
        })(),
        document.body
      )}

      {/* Context menu */}
      {contextMenu && contextItem && (
        <ContextMenu
          x={contextMenu.x}
          y={contextMenu.y}
          theme={theme}
          onClose={handleCloseContextMenu}
          onPin={handlePin}
          onUnpin={handleUnpin}
          onRename={handleOpenRename}
          onMoveToFolder={handleMoveToFolder}
          onDelete={handleDelete}
          isPinned={'isPinned' in contextItem ? contextItem.isPinned : false}
          folders={folders}
          currentFolderId={contextMenu.type === 'chat' ? (contextItem as Chat).folderId : undefined}
          isFolder={contextMenu.type === 'folder'}
        />
      )}

      {/* Rename modal */}
      <RenameModal
        isOpen={!!renameModal}
        currentName={renameModal?.currentName ?? ''}
        onClose={() => setRenameModal(null)}
        onSave={handleRename}
        theme={theme}
      />
    </div>
  )
}
